### ISSUE TITLE
Add the shortcut to undo using ctrl + z

### ISSUE THREAD

**Issue by aldovandus** [kkoomen/pointless#3]
The shortcut to undo with ctrl + z is missing. It would be useful for windows and linux users. 
I made a simple commit :
https://github.com/aldovandus/pointless/commit/9469c04082a818f83e30e51ffb089731acf15dc2
If it's ok, I can create a pull request.

**Comment by kkoomen** [comment]
Hi,

The current commands are only for MacOS, because I use MacOS myself. In order to support Windows via CTRL rather than the META key there have to be made much more changes. Either way, I'll implement them.

**Comment by kkoomen** [comment]
@aldovandus I just fixed this and merged to the `master` branch. Can you pull locally, then run `yarn run tauri dev` and check the following:

- Tooltips should display `CTRL` rather than `META`
- Executing the shown shortcuts should work, e.g.: ctrl-z

**Comment by aldovandus** [comment]
Hi @kkoomen, yes it works great now. Thank you.

**Comment by kkoomen** [comment]
@aldovandus Good to hear. Enjoy! Feel free to submit more issues or feature requests.
