### ISSUE TITLE
Reduce unnecessary re-redenders

### ISSUE THREAD

**Issue by aldovandus** [kkoomen/pointless#5]
Hi @kkoomen , I noticed that in the Paper component, there are many unnecessary re-renders. Instead, we could use composition and redux to reduce the number of re-renders with selectors. We can also store coordinates on mouse movement with useRef or createRef without calling useState and call dispatch when we need. I think we can avoid rendering the toolbar, palette, library and other icons when we are moving the cursor for example.

I attach two videos to show where re-renders occur:

https://user-images.githubusercontent.com/12563425/168416059-216d397e-ce4d-4ac1-a6f6-c93ce0c28e08.mp4

https://user-images.githubusercontent.com/12563425/168416063-4de51680-e6ff-4669-b633-17fe2f3011a0.mp4

**Comment by kkoomen** [comment]
Hi,

Good point. I did notice this myself, but haven't looked into it yet. I'll see what I can do based on your information.

**Comment by kkoomen** [comment]
@aldovandus Could you test the `feature/reduce-renders` branch? I've used refs rather than state. It does not render add unnecessary renders anymore as far as I see.

If you're happy, I'll merge it to master. If you have other suggestions, feel free to mention them.

**Comment by aldovandus** [comment]
hi @kkoomen i tested the branch feature/reduce-renders, with refs it works fine now. There are no more re-renders when moving the cursor. I think further re-renders could be avoided yet. If you want you can merge these changes into master, I will write to you as soon as I finish the analysis and testing to avoid the other re-renders.

**Comment by kkoomen** [comment]
@aldovandus Alrighty. You can comment here, I'll still read your comment(s). For now, I'll close this.
